spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: com.javatechie.dto.ProductEvent:com.javatechie.dto.ProductEvent
            add:
              type:
                headers: false